//HintName: Option.g.cs
// <auto-generated/>
#nullable enable
using dotUnion;
using System;
using dotUnion.Attributes;

namespace Tests;

partial class Hello 
{
	abstract partial record Option<T> : Union<Option<T>, Option<T>.Some, Option<T>.None>
	{
		private Option() { }
		
		public sealed partial record Some : Option<T>;
		
		public sealed partial record None : Option<T>;
		
		public static implicit operator Option<T>(T Value)
		=> new Some(Value);
		
	}
}

