//HintName: ApiResult.g.cs
// <auto-generated/>
#nullable enable
using dotUnion;
using System;
using dotUnion.Attributes;

namespace Tests;

abstract partial record ApiResult : Union<ApiResult, ApiResult.Ok, ApiResult.BadRequest>
{
	private ApiResult() { }
	
	public sealed partial record Ok : ApiResult;
	
	public sealed partial record BadRequest : ApiResult;
	
}

